title:          Napier Developers Society
tagline:        "Building things since 2013"
about:          ""

## Change url to http://0.0.0.0:4000 for local development
url:            http://napierdevsoc.github.com

markdown:       rdiscount
permalink:      pretty
highlighter:    pygments
paginate:       10
paginate_path: "page-:num"
encoding:       UTF-8

exclude:        ["README.md", "Rakefile", ".gitignore"]

github_link:   "https://github.com/NapierDevSoc"
twitter_link:  
facebook_link: "https://www.facebook.com/napierdevelopers"


gems:
  - jekyll-sitemap